### ISSUE TITLE
Refactor Help Command

### ISSUE THREAD

**Issue by pwelch** [TampaRuby/turbot#14]
The current help command currently creates a new message for each help command. With the additional plugins the command needs to be refactored.

```
current:
user: .help
turbot: .gem info Gem Name = Gem Info
turbot: .make me a sandwich = Request a tasty sandwich
turbot: ...New line for each command with description
```

Suggest making it as one response with a list of the commands and another message showing how to get more information:

```
# suggested
user: .help
turbot: .gem, .make me a sandwhich, .github status
turbot: To get more information for each command type: .help COMMAND
```

**Comment by rwjblue** [comment]
For that to work properly we need to have the plugins register themselves and their help derivatives on load.  That would allow plugins to exist without the 'cinch_plugin' suffix, and make it so that we could easily iterate over the commands available to print the initial response (thinking a hash where the keys are the commands).
